# vim: set ft=yaml ts=2 expandtab:
---

- debug: var=package_repo
  tags:
    - never
    - debug

- name: assertions
  assert:
    that:
      - ansible_os_family == 'RedHat'
      - ansible_distribution_major_version in ["7"]
      - prometheus_repo_state in [ 'present', 'absent' ]

- name: include_tasks
  include_tasks:
    file: "{{ prometheus_repo_state }}.yml"

...
