---
    
- name: prometheus is installed
  package:
    name: prometheus2
    state: present

- name: prometheus is configured
  template:
    src: prometheus.yml.j2
    dest: /etc/prometheus/prometheus.yml
    backup: true
  notify: reload prometheus

- name: prometheus is started
  service:
    name: prometheus
    state: started
    enabled: true

...
